services:
  bng-application-api:
    build:
      context: .
      target: production
    image: bng-application-api
    container_name: bng-application-api
    depends_on:
      - bng-application-api-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: bng-application-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      POSTGRES_DB: bng_application_api
      POSTGRES_HOST: ${POSTGRES_HOST:-bng-application-api-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  bng-application-api-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: bng_application_api
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
