# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  bng-application-api:
    build:
      target: development
    image: bng-application-api-development
    container_name: bng-application-api-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  bng-application-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
