# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  bng-application-api:
    build:
      target: development
    image: bng-application-api-development
    container_name: bng-application-api-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json

  bng-application-api-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
