{{- include "ffc-helm-library.container-config-map" (list . "bng-application-api.config-map") -}}
{{- define "bng-application-api.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
{{- end -}}
