{{- include "ffc-helm-library.container-secret" (list . "bng-application-api.container-secret") -}}
{{- define "bng-application-api.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
